spring:
  application:
    name: gateway-server
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:5100

management:
  endpoints:
    web:
      exposure:
        include: "*"