server:
  port: 5101

spring:
  application:
    name: eureka-server
  security:
    user:
      name: admin
      password: admin

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/