server:
  port: 5100

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dudgns0507/spring-msa-demo-config.git
          private-key: ${private-key}
          default-label: main